"use client";
import { useEffect,useState } from "react";
import Link from "next/link";

export default function NewDeal(){
 const [m,setM]=useState<any>({sellers:[],buyers:[],materials:[]}); const [form,setForm]=useState<any>({sellerId:"",buyerId:"",materialId:"",quantity:"",buyRate:"",sellRate:"",procurementType:"Surplus / Dead Stock",status:"Opportunity",freightCost:"0",loadingCost:"0",otherCost:"0",sellerCommitted:false,buyerCommitted:false}); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState("");
 useEffect(()=>{fetch("/api/master-data").then(r=>r.json()).then(setM)},[]);
 const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));
 async function save(e:any){e.preventDefault();setBusy(true);setMsg("");const r=await fetch("/api/deals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,companyId:m.companyId,quantity:Number(form.quantity),buyRate:Number(form.buyRate),sellRate:form.sellRate===""?null:Number(form.sellRate),freightCost:Number(form.freightCost),loadingCost:Number(form.loadingCost),otherCost:Number(form.otherCost)})});const d=await r.json();setBusy(false);if(!r.ok)return setMsg(d.error||"Could not create deal");location.href="/deals/"+d.id}
 return <main className="modulePage"><header className="moduleHeader"><div><p className="eyebrow">NEW COMMERCIAL RECORD</p><h1>Create Deal</h1><p className="muted">Create directly, or normally arrive here from Smart Material Finder after matching supply to buyer demand.</p></div><Link className="secondaryBtn" href="/deals">← Deals</Link></header>
 <form className="workspaceForm" onSubmit={save}><section className="workspaceCard"><h3>Parties & material</h3><div className="formGrid"><label>Seller<select required value={form.sellerId} onChange={e=>set("sellerId",e.target.value)}><option value="">Select seller</option>{m.sellers.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Buyer<select value={form.buyerId} onChange={e=>set("buyerId",e.target.value)}><option value="">Not matched yet</option>{m.buyers.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Material<select required value={form.materialId} onChange={e=>set("materialId",e.target.value)}><option value="">Select material</option>{m.materials.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Procurement type<select value={form.procurementType} onChange={e=>set("procurementType",e.target.value)}><option>Surplus / Dead Stock</option><option>Direct Corporate Purchase</option><option>Regular Supplier Purchase</option><option>Stock / Inventory Purchase</option></select></label></div></section>
 <section className="workspaceCard"><h3>Commercials</h3><div className="formGrid"><label>Quantity<input required type="number" min="0" value={form.quantity} onChange={e=>set("quantity",e.target.value)}/></label><label>Buy rate<input required type="number" min="0" value={form.buyRate} onChange={e=>set("buyRate",e.target.value)}/></label><label>Sell rate<input type="number" min="0" value={form.sellRate} onChange={e=>set("sellRate",e.target.value)} placeholder="Optional until buyer is known"/></label><label>Status<select value={form.status} onChange={e=>set("status",e.target.value)}><option>Opportunity</option><option>Negotiation</option><option>Committed</option><option>In Purchase</option></select></label><label>Freight<input type="number" min="0" value={form.freightCost} onChange={e=>set("freightCost",e.target.value)}/></label><label>Loading<input type="number" min="0" value={form.loadingCost} onChange={e=>set("loadingCost",e.target.value)}/></label><label>Other cost<input type="number" min="0" value={form.otherCost} onChange={e=>set("otherCost",e.target.value)}/></label></div></section>
 <section className="workspaceCard"><h3>Commitments</h3><div className="checkGrid"><label><input type="checkbox" checked={form.sellerCommitted} onChange={e=>set("sellerCommitted",e.target.checked)}/> Seller committed</label><label><input type="checkbox" checked={form.buyerCommitted} onChange={e=>set("buyerCommitted",e.target.checked)}/> Buyer committed</label></div></section>
 {msg&&<div className="workspaceNotice">{msg}</div>}<div className="formActions"><Link className="secondaryBtn" href="/deals">Cancel</Link><button className="saveBtn" disabled={busy}>{busy?"Creating...":"Create Deal"}</button></div>
 </form></main>;
}