"use client";
import { useState } from "react";
export default function DocumentCenter({company,purchases,salesOrders,deals,documents}:any){
 const [type,setType]=useState("PURCHASE_ORDER"); const [source,setSource]=useState(purchases[0]?.id||""); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState("");
 const sources=type==="PURCHASE_ORDER"?purchases:type==="SALES_ORDER"||type==="INVOICE"?salesOrders:deals;
 function changeType(v:string){setType(v);const next=v==="PURCHASE_ORDER"?purchases:v==="SALES_ORDER"||v==="INVOICE"?salesOrders:deals;setSource(next[0]?.id||"");}
 async function generate(format:string){if(!source)return setMsg("Select a source record first.");setBusy(true);setMsg("");try{const r=await fetch("/api/documents/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,sourceId:source,format})});const d=await r.json();if(!r.ok)throw new Error(d.detail||d.error);window.open(d.url,"_blank");setMsg(type+" generated successfully.");}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function upload(e:any){const file=e.target.files?.[0];if(!file)return;setBusy(true);setMsg("");try{const f=new FormData();f.append("file",file);f.append("documentType","SUPPORTING");f.append("reference","ERP");const r=await fetch("/api/documents/upload",{method:"POST",body:f});const d=await r.json();if(!r.ok)throw new Error(d.detail||d.error);setMsg("Supporting file uploaded.");location.reload()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 return <main style={{padding:"28px 34px",maxWidth:1250,margin:"auto",fontFamily:"Arial",color:"#172a42"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start"}}><div><div style={{fontSize:11,fontWeight:800,color:"#2b68bd",letterSpacing:1}}>DOCUMENT CENTER</div><h1 style={{margin:"6px 0",fontSize:28}}>Professional ERP Documents</h1><p style={{color:"#718096"}}>Generate standardized company documents for printing, email and digital sharing.</p></div><label style={{background:"#172a42",color:"#fff",padding:"10px 14px",borderRadius:7,fontSize:12,fontWeight:700,cursor:"pointer"}}>Upload supporting file<input type="file" accept=".pdf,image/png,image/jpeg,image/webp" onChange={upload} hidden/></label></div>
  <section style={{marginTop:24,border:"1px solid #dce4ee",borderRadius:12,padding:20,background:"#fff"}}><h2 style={{fontSize:16,marginTop:0}}>Generate document</h2><div style={{display:"grid",gridTemplateColumns:"1fr 2fr",gap:14}}>
   <label style={{fontSize:11,fontWeight:700}}>Document type<select value={type} onChange={e=>changeType(e.target.value)} style={{display:"block",width:"100%",marginTop:6,height:40,border:"1px solid #d5dee9",borderRadius:6,padding:8}}><option value="PURCHASE_ORDER">Purchase Order (PO)</option><option value="SALES_ORDER">Sales Order (SO)</option><option value="INVOICE">Invoice</option><option value="QUOTATION">Quotation</option></select></label>
   <label style={{fontSize:11,fontWeight:700}}>Source record<select value={source} onChange={e=>setSource(e.target.value)} style={{display:"block",width:"100%",marginTop:6,height:40,border:"1px solid #d5dee9",borderRadius:6,padding:8}}><option value="">Select record</option>{sources.map((x:any)=><option key={x.id} value={x.id}>{x.reference||x.id.slice(0,10)} · {x.material?.name||"Deal"} · {x.seller?.name||x.buyer?.name||x.buyerId||""}</option>)}</select></label>
  </div><div style={{display:"flex",gap:9,marginTop:18}}><button onClick={()=>generate("PDF")} disabled={busy||!source} style={{border:0,background:"#2464c4",color:"#fff",padding:"10px 16px",borderRadius:6,fontWeight:700}}>Generate PDF</button><button onClick={()=>generate("SVG")} disabled={busy||!source} style={{border:"1px solid #cbd8e7",background:"#fff",color:"#315f9e",padding:"10px 16px",borderRadius:6,fontWeight:700}}>Generate Image (SVG)</button></div>{msg&&<div style={{marginTop:12,color:"#315f9e",fontSize:12}}>{msg}</div>}</section>
  <section style={{marginTop:18,border:"1px solid #dce4ee",borderRadius:12,background:"#fff",overflow:"hidden"}}><div style={{padding:16,borderBottom:"1px solid #e8edf3",fontWeight:800}}>Recent documents</div>{documents.map((d:any)=><div key={d.id} style={{display:"grid",gridTemplateColumns:"1.5fr 1fr 1fr 100px",gap:12,padding:"12px 16px",borderBottom:"1px solid #eef1f5",fontSize:11}}><span>{d.name}</span><span>{d.reference||"—"}</span><span>{d.format} · {d.status}</span><a href={d.storageKey} target="_blank" rel="noreferrer" style={{color:"#2464c4"}}>Open</a></div>)}{!documents.length&&<div style={{padding:25,color:"#8a96a6"}}>No documents generated or uploaded yet.</div>}</section>
  <section style={{marginTop:18,padding:18,borderRadius:10,background:"#f5f8fc",border:"1px solid #dce5ef"}}><b>Company branding</b><p style={{fontSize:11,color:"#6c7a8c",lineHeight:1.6,marginBottom:0}}>Generated documents use the company name, address, contact details, tax ID and standard terms stored in the Company master. Logo support is included in the company schema and can be connected to the branding editor next.</p></section>
 </main>
}