import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { readFile } from "fs/promises";
import path from "path";
export type DocumentType = "PURCHASE_ORDER"|"SALES_ORDER"|"INVOICE"|"QUOTATION";
export type DocumentData = { type:DocumentType; number:string; date:Date; company:any; party:any; item:any[]; subtotal:number; discount:number; tax:number; total:number; paymentTerms?:string; deliveryTerms?:string; notes?:string; terms?:string };
export function titleFor(t:DocumentType){return ({PURCHASE_ORDER:"PURCHASE ORDER",SALES_ORDER:"SALES ORDER",INVOICE:"TAX INVOICE",QUOTATION:"QUOTATION"} as any)[t]||"ERP DOCUMENT"}
const money=(n:number)=>"₹"+n.toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
const safe=(v:any)=>v===undefined||v===null||v===""?"—":String(v);
const address=(c:any)=>[c.address,c.city,c.state,c.pincode].filter(Boolean).join(", ")||"Company address not configured";
export function buildSvg(d:DocumentData){
  const esc=(v:any)=>safe(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
  const text=(x:number,y:number,value:any,size=10,weight="400",fill="#172a42",anchor="start") =>
    `<text x="${x}" y="${y}" font-family="Arial,Helvetica,sans-serif" font-size="${size}" font-weight="${weight}" fill="${fill}" text-anchor="${anchor}">${esc(value)}</text>`;
  const logo=d.company.logoUrl
    ? `<image href="${esc(d.company.logoUrl)}" x="55" y="42" width="80" height="38" preserveAspectRatio="xMidYMid meet"/>`
    : "";
  const itemRows=d.item.map((x,i)=>{
    const y=315+i*34;
    const amount=x.quantity*x.rate*(1-(Number(x.discount)||0)/100);
    return `<line x1="55" y1="${y+14}" x2="739" y2="${y+14}" stroke="#e3e8ef"/>
      ${text(60,y,i+1,9)}
      ${text(82,y,x.name,9,"700")}
      ${text(82,y+14,[x.code,x.grade,x.specification].filter(Boolean).join(" · "),7,"400","#64748b")}
      ${text(390,y,x.quantity.toLocaleString("en-IN"),9,"400","#172a42","end")}
      ${text(440,y,x.unit,9)}
      ${text(535,y,money(x.rate),9,"400","#172a42","end")}
      ${text(585,y,(Number(x.discount)||0)+"%",9,"400","#172a42","end")}
      ${text(735,y,money(amount),9,"700","#172a42","end")}`;
  }).join("");
  const startY=315;
  const totalsY=Math.max(startY+d.item.length*34+35,520);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="794" height="1123" viewBox="0 0 794 1123">
    <rect width="794" height="1123" fill="#ffffff"/>
    <rect x="32" y="32" width="730" height="1059" fill="none" stroke="#d9e0e8"/>
    ${logo}
    ${text(d.company.logoUrl?145:55,72,d.company.name,20,"700","#172a42")}
    ${text(55,94,address(d.company),9,"400","#64748b")}
    ${text(735,76,titleFor(d.type),18,"700","#1f5fc9","end")}
    ${text(735,96,"No. "+d.number,10,"400","#475569","end")}
    ${text(735,112,"Date: "+d.date.toLocaleDateString("en-IN"),10,"400","#475569","end")}
    <line x1="55" y1="130" x2="739" y2="130" stroke="#d9e0e8"/>
    <rect x="55" y="150" width="330" height="86" rx="6" fill="#f6f8fb"/>
    ${text(70,172,"PARTY",9,"700","#64748b")}
    ${text(70,194,d.party?.name,13,"700","#172a42")}
    ${text(70,214,address(d.party||{}),8,"400","#64748b")}
    <rect x="55" y="270" width="684" height="32" rx="4" fill="#172a42"/>
    ${text(60,291,"#",9,"700","#ffffff")}
    ${text(82,291,"ITEM",9,"700","#ffffff")}
    ${text(390,291,"QTY",9,"700","#ffffff","end")}
    ${text(440,291,"UNIT",9,"700","#ffffff")}
    ${text(535,291,"RATE",9,"700","#ffffff","end")}
    ${text(585,291,"DISC.",9,"700","#ffffff","end")}
    ${text(735,291,"AMOUNT",9,"700","#ffffff","end")}
    ${itemRows}
    <line x1="475" y1="${totalsY-18}" x2="739" y2="${totalsY-18}" stroke="#d9e0e8"/>
    ${text(500,totalsY,"Subtotal",10,"400","#64748b")}
    ${text(735,totalsY,money(d.subtotal),10,"400","#172a42","end")}
    ${text(500,totalsY+22,"Discount",10,"400","#64748b")}
    ${text(735,totalsY+22,"-"+money(d.discount),10,"400","#172a42","end")}
    ${text(500,totalsY+44,"Tax",10,"400","#64748b")}
    ${text(735,totalsY+44,money(d.tax),10,"400","#172a42","end")}
    <rect x="475" y="${totalsY+60}" width="264" height="44" rx="5" fill="#eef5ff"/>
    ${text(490,totalsY+88,"TOTAL",11,"700","#172a42")}
    ${text(725,totalsY+88,money(d.total),15,"700","#1f5fc9","end")}
    ${text(55,totalsY+15,"TERMS & NOTES",9,"700","#64748b")}
    ${text(55,totalsY+37,d.terms||d.notes||"",9,"400","#475569")}
    ${text(55,1020,"Authorized Signatory",9,"400","#64748b")}
    <line x1="55" y1="1005" x2="300" y2="1005" stroke="#94a3b8"/>
    ${text(735,1065,"Generated by Steel Trading ERP",7,"400","#94a3b8","end")}
  </svg>`;
}
export async function buildPdf(d:DocumentData){
 const pdf=await PDFDocument.create(); const page=pdf.addPage([595,842]); const font=await pdf.embedFont(StandardFonts.Helvetica); const bold=await pdf.embedFont(StandardFonts.HelveticaBold);
 const blue=rgb(.12,.37,.79),dark=rgb(.09,.16,.25),muted=rgb(.38,.44,.51),line=rgb(.85,.88,.91);
 const t=(s:string,x:number,y:number,size=8,f=font,color=dark)=>page.drawText(s,{x,y,size,font:f,color});
 if(d.company.logoUrl){try{const raw=await readFile(path.join(process.cwd(),"public",d.company.logoUrl.replace(/^\//,"")));const img=d.company.logoUrl.toLowerCase().endsWith(".png")?await pdf.embedPng(raw):await pdf.embedJpg(raw); page.drawImage(img,{x:40,y:780,width:58,height:30});}catch{}} t(safe(d.company.name),108,800,16,bold); t(address(d.company),40,785,7,font,muted); t(titleFor(d.type),410,800,14,bold,blue); t("No. "+d.number,410,784,8,font,muted); t("Date: "+d.date.toLocaleDateString("en-IN"),410,772,8,font,muted); page.drawLine({start:{x:40,y:755},end:{x:555,y:755},thickness:1,color:line});
 page.drawRectangle({x:40,y:680,width:250,height:55,color:rgb(.965,.975,.985)}); t("PARTY",52,717,7,bold,muted); t(safe(d.party?.name),52,700,10,bold); t(address(d.party||{}),52,687,7,font,muted);
 let y=635; page.drawRectangle({x:40,y:y-14,width:515,height:20,color:dark}); ["#","ITEM","QTY","UNIT","RATE","DISC","AMOUNT"].forEach((h,i)=>t(h,[40,60,325,375,410,470,515][i],y-8,7,bold,undefined as any,rgb(1,1,1))); y-=28;
 d.item.forEach((x,i)=>{const amount=x.quantity*x.rate*(1-x.discount/100); t(String(i+1),40,y,7); t(safe(x.name).slice(0,42),60,y,7); t(x.quantity.toLocaleString("en-IN"),325,y,7); t(x.unit,375,y,7); t(money(x.rate),410,y,7); t(x.discount+"%",470,y,7); t(money(amount),515,y,7); y-=22; page.drawLine({start:{x:40,y:y+10},end:{x:555,y:y+10},thickness:.5,color:line});});
 y=Math.max(y,380); t("Subtotal",410,y,8,font,muted); t(money(d.subtotal),515,y,8); y-=18; t("Discount",410,y,8,font,muted); t("-"+money(d.discount),515,y,8); y-=18; t("Tax",410,y,8,font,muted); t(money(d.tax),515,y,8); y-=25; page.drawRectangle({x:400,y:y-7,width:155,height:28,color:rgb(.93,.96,1)}); t("TOTAL",412,y+3,9,bold); t(money(d.total),490,y+3,10,bold,undefined as any,blue);
 y-=55; t("TERMS & NOTES",40,y,8,bold,muted); y-=15; t(safe(d.terms||d.notes),40,y,7,font,muted); t("Authorized Signatory",40,90,8,font,muted); page.drawLine({start:{x:40,y:105},end:{x:190,y:105},thickness:.7,color:muted}); t("Generated by Steel Trading ERP",40,45,6,font,muted);
 return pdf.save();
}