"use client";
import { useEffect,useState } from "react";
export default function Branding(){
 const [f,setF]=useState<any>({}); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/company").then(r=>r.json()).then(setF)},[]);
 const save=async()=>{setBusy(true);setMsg("");const r=await fetch("/api/company",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)});const d=await r.json();setMsg(r.ok?"Company branding saved.":d.error||"Save failed");setBusy(false)};
 return <main style={{padding:32,maxWidth:1050,margin:"auto",fontFamily:"Arial",color:"#172a42"}}>
  <div style={{fontSize:11,fontWeight:800,color:"#2b68bd",letterSpacing:1}}>DOCUMENT SETTINGS</div><h1 style={{margin:"6px 0"}}>Company Branding & Document Settings</h1><p style={{color:"#718096"}}>These values are reused automatically across purchase orders, sales orders, invoices and quotations.</p>
  <section style={{background:"#fff",border:"1px solid #dce4ee",borderRadius:12,padding:22,marginTop:22}}>
   <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14}}>{[["name","Company name"],["code","Company code"],["address","Address"],["city","City"],["state","State"],["pincode","Pincode"],["phone","Phone"],["email","Email"],["website","Website"],["taxId","Tax / GST ID"]].map(([k,l])=><label key={k} style={{fontSize:11,fontWeight:700}}>{l}<input value={f[k]||""} onChange={e=>setF({...f,[k]:e.target.value})} style={{display:"block",width:"100%",marginTop:5,height:38,border:"1px solid #d6dfe9",borderRadius:6,padding:"0 9px"}}/></label>)}</div>
   <div style={{marginTop:18,padding:14,border:"1px solid #dce5ef",borderRadius:8,background:"#f8fafc"}}><b style={{fontSize:11}}>Document numbering</b><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10,marginTop:10}}>{[["purchaseOrderPrefix","PO prefix"],["salesOrderPrefix","SO prefix"],["invoicePrefix","Invoice prefix"],["quotationPrefix","Quotation prefix"]].map(([k,l])=><label key={k} style={{fontSize:10,fontWeight:700}}>{l}<input value={f[k]||""} onChange={e=>setF({...f,[k]:e.target.value.toUpperCase()})} style={{display:"block",width:"100%",marginTop:4,height:34,border:"1px solid #d6dfe9",borderRadius:5,padding:"0 8px"}}/></label>)}</div><p style={{fontSize:9,color:"#718096"}}>New documents use PREFIX-YYYY-000001. Later revisions keep the same number and increment the version.</p></div>
   <label style={{display:"block",marginTop:16,fontSize:11,fontWeight:700}}>Standard terms & conditions<textarea value={f.documentTerms||""} onChange={e=>setF({...f,documentTerms:e.target.value})} rows={5} style={{display:"block",width:"100%",marginTop:5,border:"1px solid #d6dfe9",borderRadius:6,padding:9}}/></label>
   <div style={{marginTop:18,display:"flex",justifyContent:"flex-end",alignItems:"center",gap:12}}><span style={{fontSize:11,color:"#2b68bd"}}>{msg}</span><button onClick={save} disabled={busy} style={{background:"#2464c4",color:"#fff",border:0,borderRadius:6,padding:"10px 17px",fontWeight:700}}>Save settings</button></div>
  </section>
 </main>
}